spring:
  profiles:
    active: dev

server:
  servlet.context-path: /v1
    
---
spring:
  profiles: dev
  datasource: 
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

notification:
  wsServerUrl: 'http://localhost:5000/event/order-creation'